package uz.educenter.bot.state;

public enum UserState {
    NONE,
    WAITING_APPLICATION_FULL_NAME,
    WAITING_APPLICATION_PHONE,
    WAITING_APPLICATION_MESSAGE,
    WAITING_ADMIN_PASSWORD,
    WAITING_ADMIN_NEW_GROUP_NAME,
    WAITING_ADMIN_NEW_GROUP_DAYS,
    WAITING_ADMIN_NEW_GROUP_START_TIME,
    WAITING_ADMIN_NEW_GROUP_END_TIME,
    WAITING_ADMIN_NEW_GROUP_START_DATE,
    WAITING_ADMIN_NEW_GROUP_END_DATE
}