bot.username=braindevelopment_bot
bot.token=8675533396:AAF5Ox3XPlTN3wGbWNdwEspkjNv6XHG2B9I

db.url=jdbc:postgresql://localhost:5432/education_center
db.username=postgres
db.password=1985

center.address=Toshkent shahri, Mirzo Ulug'bek tumani , Chust ko'chasi, 17 
center.location_url=https://www.google.com/maps/place/41%C2%B019'49.8%22N+69%C2%B019'58.0%22E/@41.3296086,69.3289069,1256m/data=!3m1!1e3!4m4!3m3!8m2!3d41.330499!4d69.332764?entry=ttu&g_ep=EgoyMDI2MDMxMS4wIKXMDSoASAFQAw%3D%3D
teacher1.username=@Jumaniyazov_Bobur
teacher2.username=@maruf_in