bot.username=YOUR_BOT_USERNAME
bot.token=YOUR_BOT_TOKEN

db.url=jdbc:postgresql://localhost:5432/education_center
db.username=postgres
db.password=YOUR_DB_PASSWORD

center.address=YOUR_CENTER_ADDRESS
center.location_url=YOUR_LOCATION_URL
teacher1.username=@teacher_one
teacher2.username=@teacher_two